### ISSUE TITLE
[Forge 1.20.1] Crash after joining world (java.lang.IllegalArgumentException)

### ISSUE THREAD

**Issue by Yldales** [AstralOrdana/Immersive-Weathering#315] opened 2023-12-29 12:04 UTC
Hi,

**Describe the bug:**
Minecraft crash after joining a singleplayer world.

**Versions**: 
- Minecraft version: 1.20.1
- Immersive Weathering version: 1.20.2-1.3.0
- Moonlight Lib version: 1.20-2.8.78 
- Fabric API / QSL / Forge version: Forge 1.20.1-47.2.19

**Other mods:**
None.

**Logs:**
- crash-2023-12-29_12.56.16-server.txt : https://pastebin.com/raw/spUAxmEu

**To Reproduce:**
Steps to reproduce the behavior. Format it as a numbered list of steps.
1. Start Minecraft with [Forge 1.20.1-47.2.19](https://maven.minecraftforge.net/net/minecraftforge/forge/1.20.1-47.2.19/forge-1.20.1-47.2.19-installer.jar), [Moonlight 1.20-2.8.78](https://mediafilez.forgecdn.net/files/4991/483/moonlight-1.20-2.8.78-forge.jar) and [Immersive Weathering 1.20.2-1.3.0](https://mediafilez.forgecdn.net/files/4991/530/immersive_weathering-1.20.2-1.3.0-forge.jar).
2. Create a new singleplayer world with the default options.
3. Once at 100%, Minecraft should crash.

**Expected behavior:**
Minecraft shouldn't crash.

**Screenshots:**
None.

**Additional info:**
None.

**Comment by MehVahdJukaar** [comment] 2023-12-29 12:38
duplicate of one below

**Closed as completed by MehVahdJukaar** 2023-12-29 12:38 UTC
