### ISSUE TITLE
Datapack error 1.18.2-1.2.0

### ISSUE THREAD

**Issue by agentwolf88** [AstralOrdana/Immersive-Weathering#50] opened 2022-04-22 19:29 UTC
Forge :40.1.0

https://0x0.st/oTu1.txt

**Comment by MehVahdJukaar** [comment] 2022-04-23 00:37
I'm not sure what causes this. I cant replicate it of course but I've had another report of this. My guess is that it has something to do with another mod and until that is found I cant really do much

**Comment by Zano1999** [comment] 2022-04-23 05:26
> Forge :40.1.0
> 
> https://0x0.st/oTu1.txt

I have the same problem, could you post the list of your mods so I can see which ones we have in common?

**Comment by MehVahdJukaar** [comment] 2022-04-23 18:16
should be fixed. was partially caused by optifric

**Closed by MehVahdJukaar** 2022-04-23 18:16 UTC

**Comment by Zano1999** [comment] 2022-04-23 18:20
I use forge, i don't have optifabric

**Comment by MehVahdJukaar** [comment] 2022-04-24 18:41
I said optifrick not optimal fabric xD. Still it should have been fixed with yesterday's patches

**Comment by Zano1999** [comment] 2022-04-24 18:43
Yes, is fixed now :)
