### ISSUE TITLE
Stone and cobblestone wall glitch

### ISSUE THREAD

**Issue by FlyingNokk** [AstralOrdana/Immersive-Weathering#263] opened 2023-04-07 21:33 UTC
Sandy and snowy versions of stone, stone bricks and cobblestone walls are getting purple black graphic the moment they get snowy or sandy altough sandy stone wall, sandy stone brick wall and sandy cobblestone wall have only glitched icons

Minecraft version: 1.19.2
Immersive Weathering version: immersive_weathering-1.19.2-1.2.9-forge.jar
Moonlight Lib version: 1.19.2.2.2.27
Fabric API / QSL / Forge version: 43.2.4 forge

.

![2023-04-07_23 29 56](https://user-images.githubusercontent.com/130186379/230681624-7695a172-c1db-48e3-9da5-c18aa8004c6c.png)

**Comment by ButterMe8aby** [comment] 2023-06-10 22:56
I'm having this same issue, honestly just a resourcepack I could load to fix this would be enough but I'm not sure where to get that.

**Comment by AstralOrdana** [comment] 2023-06-10 22:58
duplicate of known issue [https://github.com/AstralOrdana/Immersive-Weathering/issues/251](251) with temporary solution

**Closed as completed by AstralOrdana** 2023-06-10 22:58 UTC
