### ISSUE TITLE
Snowy Stone Brick Wall missing texture 1.19.2

### ISSUE THREAD

**Issue by ebaystudio** [AstralOrdana/Immersive-Weathering#292] opened 2023-07-20 21:26 UTC
This is from the newest 1.19.2 version 19.5 of Better Minecraft Mod pack for Fabric. 

I've noticed the Snowy Stone Brick Wall texture is missing when updating from the seasonal changes. Pink and black. 

Also not sure if it's a bug but the Frosted Glass is really random. I have a bunch of display cases inside my castle and out of the hundreds of pane-glass blocks one 1 or 2 will change at any time during the winter.

**Comment by AstralOrdana** [comment] 2023-07-20 21:28
duplicate of known issue https://github.com/AstralOrdana/Immersive-Weathering/issues/251 with temporary solution

**Closed as completed by AstralOrdana** 2023-07-20 21:28 UTC

**Comment by ebaystudio** [comment] 2023-07-20 23:15
Thanks
