### ISSUE TITLE
[FORGE 1.20.1] Game crashed due to illegal value.

### ISSUE THREAD

**Issue by Iamuserin9112001** [AstralOrdana/Immersive-Weathering#345] opened 2024-02-25 05:52 UTC
During playing to my survival world. A sudden error caused the game to crash due to "illegal value", according to the output message.
`The game crashed whilst exception ticking world
Error: java.lang.IllegalArgumentException: Cannot set property IntegerProperty{name=layers, clazz=class java.lang.Integer, values=[0, 1, 2, 3, 4, 5, 6, 7, 8]} to -1 on Block{immersive_weathering:jungle_leaf_pile}, it is not an allowed value`
Fully detailed:
https://mclo.gs/TVrUS1n

**Comment by AstralOrdana** [comment] 2024-02-25 18:43
duplicate of #327, update the mod

**Closed as completed by AstralOrdana** 2024-02-25 18:43 UTC
