### ISSUE TITLE
Missing particle descriptions disabling resourcepacks

### ISSUE THREAD

**Issue by magneticflux-** [AstralOrdana/Immersive-Weathering#164] opened 2022-10-23 23:38 UTC
**Describe the bug:**
When loading with Aurora's Deco or BYG, the leaf particles are unable to be loaded and cause resourcepacks to be reset.

**Versions: (BEFORE SUBMITTING A BUG REPORT, make sure you have the most up-to-date versions of Immersive Weathering, Moonlight Lib and Supplementaries)**
Minecraft version: `1.19.2`
Immersive Weathering version: `1.19.2-1.1.2`
Fabric API / QSL / Forge version: `4.0.0-beta.17+0.64.0-1.19.2`/`3.0.0-beta.19+1.19.2`

**Other mods:**
```
[18:19:03] [main/INFO]: Loading 95 mods:
| Index | Mod                                               | ID                                            | Version                      |
|------:|---------------------------------------------------|-----------------------------------------------|------------------------------|
|    37 | Aurora's Decorations                              | aurorasdeco                                   | 1.0.0-beta.9+1.19            |
|    89 | Charm                                             | charm                                         | 4.4.4                        |
|    71 | Charmonium                                        | charmonium                                    | 4.2.1                        |
|     0 | Immersive Weathering                              | immersive_weathering                          | 1.19.2-1.1.2                 |
|    56 | Minecraft                                         | minecraft                                     | 1.19.2                       |
|     4 | Moonlight                                         | moonlight                                     | 1.19.2-2.1.3                 |
|     7 | Oh The Biomes You'll Go                           | byg                                           | 2.0.0.13                     |
|    20 | OpenJDK 64-Bit Server VM                          | java                                          | 19                           |
|    92 | Quilt Advancement API                             | quilt_advancement                             | 3.0.0-beta.19+1.19.2         |
|    65 | Quilt Base API                                    | quilt_base                                    | 3.0.0-beta.19+1.19.2         |
|    91 | Quilt Biome API                                   | quilt_biome                                   | 3.0.0-beta.19+1.19.2         |
|    85 | Quilt Block Content Registry API                  | quilt_block_content_registry                  | 3.0.0-beta.19+1.19.2         |
|    58 | Quilt Block Entity API                            | quilt_block_entity                            | 3.0.0-beta.19+1.19.2         |
|    31 | Quilt Block Extensions API                        | quilt_block_extensions                        | 3.0.0-beta.19+1.19.2         |
|    90 | Quilt Client Command API                          | quilt_client_command                          | 3.0.0-beta.19+1.19.2         |
|    30 | Quilt Command API                                 | quilt_command                                 | 3.0.0-beta.19+1.19.2         |
|    86 | Quilt Crash Info                                  | quilt_crash_info                              | 3.0.0-beta.19+1.19.2         |
|    73 | Quilt DataFixerUpper API                          | quilt_datafixerupper                          | 3.0.0-beta.19+1.19.2         |
|    48 | Quilt Dimension API                               | quilt_dimension                               | 3.0.0-beta.19+1.19.2         |
|    68 | Quilt Entity API                                  | quilt_entity                                  | 3.0.0-beta.19+1.19.2         |
|    57 | Quilt Entity Events                               | quilt_entity_events                           | 3.0.0-beta.19+1.19.2         |
|    50 | Quilt Entity Networking API                       | quilt_entity_networking                       | 3.0.0-beta.19+1.19.2         |
|    14 | Quilt Item Content Registry API                   | quilt_item_content_registry                   | 3.0.0-beta.19+1.19.2         |
|    72 | Quilt Item Extension API                          | quilt_item_extension                          | 3.0.0-beta.19+1.19.2         |
|    15 | Quilt Item Group API                              | quilt_item_group                              | 3.0.0-beta.19+1.19.2         |
|     9 | Quilt Item Setting API                            | quilt_item_setting                            | 3.0.0-beta.19+1.19.2         |
|    66 | Quilt Lifecycle Events                            | quilt_lifecycle_events                        | 3.0.0-beta.19+1.19.2         |
|    93 | Quilt Loader                                      | quilt_loader                                  | 0.17.5-beta.10               |
|    23 | Quilt Multipart Entity API                        | quilt_entity_multipart                        | 3.0.0-beta.19+1.19.2         |
|    34 | Quilt Networking                                  | quilt_networking                              | 3.0.0-beta.19+1.19.2         |
|    69 | Quilt Points of Interest                          | quilt_points_of_interest                      | 3.0.0-beta.19+1.19.2         |
|    43 | Quilt Recipe API                                  | quilt_recipe                                  | 3.0.0-beta.19+1.19.2         |
|    17 | Quilt Registry API                                | quilt_registry                                | 3.0.0-beta.19+1.19.2         |
|    83 | Quilt Registry Entry Attachment                   | quilt_registry_entry_attachment               | 3.0.0-beta.19+1.19.2         |
|    24 | Quilt Resource Loader                             | quilt_resource_loader                         | 3.0.0-beta.19+1.19.2         |
|    21 | Quilt Screen API                                  | quilt_screen                                  | 3.0.0-beta.19+1.19.2         |
|    51 | Quilt Surface Rule API                            | quilt_surface_rule                            | 3.0.0-beta.19+1.19.2         |
|    25 | Quilt Tags API                                    | quilt_tags                                    | 3.0.0-beta.19+1.19.2         |
|    52 | Quilt Tooltip API                                 | quilt_tooltip                                 | 3.0.0-beta.19+1.19.2         |
|    53 | Quilt Vehicle API                                 | quilt_vehicle                                 | 3.0.0-beta.19+1.19.2         |
|    59 | Quilt Villager API                                | quilt_villager                                | 3.0.0-beta.19+1.19.2         |
|    35 | Quilted Fabric API                                | quilted_fabric_api                            | 4.0.0-beta.17+0.64.0-1.19.2  |
|    79 | Quilted Fabric API Base                           | quilted_fabric_api_base                       | 4.0.0-beta.17+0.64.0-1.19.2  |
|    12 | Quilted Fabric API Lookup API (v1)                | quilted_fabric_api_lookup_api_v1              | 4.0.0-beta.17+0.64.0-1.19.2  |
|    75 | Quilted Fabric Biome API (v1)                     | quilted_fabric_biome_api_v1                   | 4.0.0-beta.17+0.64.0-1.19.2  |
|    87 | Quilted Fabric BlockRenderLayer Registration (v1) | quilted_fabric_blockrenderlayer_v1            | 4.0.0-beta.17+0.64.0-1.19.2  |
|    84 | Quilted Fabric Client Tags                        | quilted_fabric_client_tags_api_v1             | 4.0.0-beta.17+0.64.0-1.19.2  |
|    44 | Quilted Fabric Command API (v1)                   | quilted_fabric_command_api_v1                 | 4.0.0-beta.17+0.64.0-1.19.2  |
|    47 | Quilted Fabric Command API (v2)                   | quilted_fabric_command_api_v2                 | 4.0.0-beta.17+0.64.0-1.19.2  |
|    38 | Quilted Fabric Commands (v0)                      | quilted_fabric_commands_v0                    | 4.0.0-beta.17+0.64.0-1.19.2  |
|    62 | Quilted Fabric Containers (v0)                    | quilted_fabric_containers_v0                  | 4.0.0-beta.17+0.64.0-1.19.2  |
|    80 | Quilted Fabric Content Registries (v0)            | quilted_fabric_content_registries_v0          | 4.0.0-beta.17+0.64.0-1.19.2  |
|    63 | Quilted Fabric Convention Tags API (v1)           | quilted_fabric_convention_tags_api_v1         | 4.0.0-beta.17+0.64.0-1.19.2  |
|    27 | Quilted Fabric Crash Report Info (v1)             | quilted_fabric_crash_report_info_v1           | 4.0.0-beta.17+0.64.0-1.19.2  |
|    88 | Quilted Fabric Data Generation API (v1)           | quilted_fabric_data_generation_api_v1         | 4.0.0-beta.17+0.64.0-1.19.2  |
|    40 | Quilted Fabric Dimensions API (v1)                | quilted_fabric_dimensions_v1                  | 4.0.0-beta.17+0.64.0-1.19.2  |
|    61 | Quilted Fabric Entity Events (v1)                 | quilted_fabric_entity_events_v1               | 4.0.0-beta.17+0.64.0-1.19.2  |
|    49 | Quilted Fabric Events Interaction (v0)            | quilted_fabric_events_interaction_v0          | 4.0.0-beta.17+0.64.0-1.19.2  |
|    78 | Quilted Fabric Events Lifecycle (v0)              | quilted_fabric_events_lifecycle_v0            | 4.0.0-beta.17+0.64.0-1.19.2  |
|    33 | Quilted Fabric Game Rule API (v1)                 | quilted_fabric_game_rule_api_v1               | 4.0.0-beta.17+0.64.0-1.19.2  |
|    70 | Quilted Fabric Item API (v1)                      | quilted_fabric_item_api_v1                    | 4.0.0-beta.17+0.64.0-1.19.2  |
|    18 | Quilted Fabric Item Groups (v0)                   | quilted_fabric_item_groups_v0                 | 4.0.0-beta.17+0.64.0-1.19.2  |
|    94 | Quilted Fabric Key Binding API (v1)               | quilted_fabric_key_binding_api_v1             | 4.0.0-beta.17+0.64.0-1.19.2  |
|    64 | Quilted Fabric Key Bindings (v0)                  | quilted_fabric_keybindings_v0                 | 4.0.0-beta.17+0.64.0-1.19.2  |
|     8 | Quilted Fabric Lifecycle Events (v1)              | quilted_fabric_lifecycle_events_v1            | 4.0.0-beta.17+0.64.0-1.19.2  |
|    46 | Quilted Fabric Loot API (v2)                      | quilted_fabric_loot_api_v2                    | 4.0.0-beta.17+0.64.0-1.19.2  |
|    13 | Quilted Fabric Loot Tables (v1)                   | quilted_fabric_loot_tables_v1                 | 4.0.0-beta.17+0.64.0-1.19.2  |
|    77 | Quilted Fabric Message API (v1)                   | quilted_fabric_message_api_v1                 | 4.0.0-beta.17+0.64.0-1.19.2  |
|    82 | Quilted Fabric Mining Level API (v1)              | quilted_fabric_mining_level_api_v1            | 4.0.0-beta.17+0.64.0-1.19.2  |
|    76 | Quilted Fabric Models (v0)                        | quilted_fabric_models_v0                      | 4.0.0-beta.17+0.64.0-1.19.2  |
|    32 | Quilted Fabric Networking (v0)                    | quilted_fabric_networking_v0                  | 4.0.0-beta.17+0.64.0-1.19.2  |
|    22 | Quilted Fabric Networking API (v1)                | quilted_fabric_networking_api_v1              | 4.0.0-beta.17+0.64.0-1.19.2  |
|    60 | Quilted Fabric Object Builder API (v1)            | quilted_fabric_object_builder_api_v1          | 4.0.0-beta.17+0.64.0-1.19.2  |
|    81 | Quilted Fabric Particles (v1)                     | quilted_fabric_particles_v1                   | 4.0.0-beta.17+0.64.0-1.19.2  |
|    55 | Quilted Fabric Registry Sync (v0)                 | quilted_fabric_registry_sync_v0               | 4.0.0-beta.17+0.64.0-1.19.2  |
|    10 | Quilted Fabric Renderer - Indigo                  | quilted_fabric_renderer_indigo                | 4.0.0-beta.17+0.64.0-1.19.2  |
|    19 | Quilted Fabric Renderer API (v1)                  | quilted_fabric_renderer_api_v1                | 4.0.0-beta.17+0.64.0-1.19.2  |
|    36 | Quilted Fabric Renderer Registries (v1)           | quilted_fabric_renderer_registries_v1         | 4.0.0-beta.17+0.64.0-1.19.2  |
|    26 | Quilted Fabric Rendering (v0)                     | quilted_fabric_rendering_v0                   | 4.0.0-beta.17+0.64.0-1.19.2  |
|    28 | Quilted Fabric Rendering (v1)                     | quilted_fabric_rendering_v1                   | 4.0.0-beta.17+0.64.0-1.19.2  |
|    54 | Quilted Fabric Rendering Data Attachment (v1)     | quilted_fabric_rendering_data_attachment_v1   | 4.0.0-beta.17+0.64.0-1.19.2  |
|    16 | Quilted Fabric Rendering Fluids (v1)              | quilted_fabric_rendering_fluids_v1            | 4.0.0-beta.17+0.64.0-1.19.2  |
|    39 | Quilted Fabric Resource Conditions API (v1)       | quilted_fabric_resource_conditions_api_v1     | 4.0.0-beta.17+0.64.0-1.19.2  |
|    67 | Quilted Fabric Resource Loader (v0)               | quilted_fabric_resource_loader_v0             | 4.0.0-beta.17+0.64.0-1.19.2  |
|    74 | Quilted Fabric Screen API (v1)                    | quilted_fabric_screen_api_v1                  | 4.0.0-beta.17+0.64.0-1.19.2  |
|    41 | Quilted Fabric Screen Handler API (v1)            | quilted_fabric_screen_handler_api_v1          | 4.0.0-beta.17+0.64.0-1.19.2  |
|    42 | Quilted Fabric Sound API (v1)                     | quilted_fabric_sound_api_v1                   | 4.0.0-beta.17+0.64.0-1.19.2  |
|    45 | Quilted Fabric Textures (v0)                      | quilted_fabric_textures_v0                    | 4.0.0-beta.17+0.64.0-1.19.2  |
|    29 | Quilted Fabric Transfer API (v1)                  | quilted_fabric_transfer_api_v1                | 4.0.0-beta.17+0.64.0-1.19.2  |
|    11 | Quilted Fabric Transitive Access Wideners (v1)    | quilted_fabric_transitive_access_wideners_v1  | 4.0.0-beta.17+0.64.0-1.19.2  |
|     5 | TerraBlender                                      | terrablender                                  | 2.0.1.128                    |
|     3 | Terraform Wood API (v1)                           | terraform-wood-api-v1                         | 4.1.0                        |
|     1 | core                                              | com_electronwill_night-config_core            | 3.6.6                        |
|     6 | toml                                              | com_electronwill_night-config_toml            | 3.6.6                        |
|     2 | toml4j                                            | com_moandjiezana_toml_toml4j                  | 0.7.2                        |
|------:|---------------------------------------------------|-----------------------------------------------|------------------------------|
```

**Logs:**
*Even if the game does not crash they may be useful!*
Please provide the following logs:
From .minecraft/logs :  "latest.log" as well as "debug.log" if it exists. From .minecraft : "launcher_log" as well as a
file that starts with "hs_err" if it exists. Note: Double check that the logs are from the correct time. ex, don't give
us a log from a month ago because you forgot to check the date.
```
[18:19:33] [Render thread/INFO]: Caught error loading resourcepacks, removing all selected resourcepacks
java.util.concurrent.CompletionException: java.lang.IllegalStateException: Failed to load description for particle immersive_weathering:byg/red_maple_leaf
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1807) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1311) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1841) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1806) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177) ~[?:?]
Caused by: java.lang.IllegalStateException: Failed to load description for particle immersive_weathering:byg/red_maple_leaf
	at net.minecraft.class_702.method_18836(class_702.java:281) ~[client-intermediary.jar:?]
	at net.minecraft.class_702.method_18837(class_702.java:228) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
	... 6 more
Caused by: java.io.FileNotFoundException: immersive_weathering:particles/byg/red_maple_leaf.json
	at net.minecraft.class_5912.method_43043(class_5912.java:20) ~[client-intermediary.jar:?]
	at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
	at net.minecraft.class_5912.getResourceOrThrow(class_5912.java:20) ~[client-intermediary.jar:?]
	at net.minecraft.class_5912.openAsReader(class_5912.java:28) ~[client-intermediary.jar:?]
	at net.minecraft.class_702.method_18836(class_702.java:265) ~[client-intermediary.jar:?]
	at net.minecraft.class_702.method_18837(class_702.java:228) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
	... 6 more
```
[latest.log](https://github.com/AstralOrdana/Immersive-Weathering/files/9847821/latest.log)

**To Reproduce:**
1. Install the mods
2. Start the game
3. Check the logs

**Expected behavior:**
No errors :)

**Comment by AstralOrdana** [comment] 2022-10-24 21:17
duplicate of #165

**Closed as completed by AstralOrdana** 2022-10-24 21:17 UTC
