### ISSUE TITLE
The name of the category is lost

### ISSUE THREAD

**Issue by BlackAures1** [AstralOrdana/Immersive-Weathering#286] opened 2023-07-07 15:18 UTC
immersive_weathering-1.19.2-1.2.9-forge
You have lost localization
![2023-07-07_18 15 45](https://github.com/AstralOrdana/Immersive-Weathering/assets/43911230/a6d13a7a-8dc1-4be4-8fde-a94a82d435b6)
![image](https://github.com/AstralOrdana/Immersive-Weathering/assets/43911230/f48e5f32-5646-410e-b628-e6a568fe7431)

**Comment by AstralOrdana** [comment] 2023-08-06 16:51
duplicate of existing closed issue

**Closed as completed by AstralOrdana** 2023-08-06 16:51 UTC
