### ISSUE TITLE
Immersive Weathering - Server crashes after explosions

### ISSUE THREAD

**Issue by McPersson** [AstralOrdana/Immersive-Weathering#329] opened 2024-02-04 20:54 UTC
I was happily detonating nukes (from Alex's Caves mod) in the forest. Everything was burning, everything was fine. But at one point the server started to crash. I realised from the logs that there was something wrong with Immersive Weathering. Until then, I had not encountered such an error during long gaming sessions. With this mod removed, everything worked.

Minecraft version: 1.20.1
Immersive Weathering version: immersive_weathering-1.20.1-2.0.0-forge
Moonlight Lib version: moonlight-1.20-2.9.7-forge
Forge version: 47.2.20

Other mods:

![image](https://github.com/AstralOrdana/Immersive-Weathering/assets/50740709/b3686245-6fb6-4973-a83b-d618d456e7fd)

Logs: [crash-2024-02-05_00.39.37-server.txt](https://github.com/AstralOrdana/Immersive-Weathering/files/14158435/crash-2024-02-05_00.39.37-server.txt)

To Reproduce:
1. Nuke the forest so everything burns.

**Comment by AstralOrdana** [comment] 2024-02-06 04:36
duplicate of #327

**Closed as completed by AstralOrdana** 2024-02-06 04:36 UTC
