### ISSUE TITLE
Game crashes when I try to apply moss onto a piece of cobblestone.

### ISSUE THREAD

**Issue by misfit-stag** [AstralOrdana/Immersive-Weathering#333] opened 2024-02-09 16:59 UTC
**Describe the bug:**
Title pretty much says it all. Something about a quark incompatibility? You can't use Quark's moss ball, but trying to use the IW's clump crashes to desktop.

**Versions: (BEFORE SUBMITTING A BUG REPORT, make sure you have the most up-to-date versions of Immersive Weathering, Moonlight Lib and Supplementaries)**

Minecraft version: 1.20.1
Immersive Weathering version: 1.20.1-2.0.0
Moonlight Lib version: 1.20-2.9.8
Fabric API / QSL / Forge version: 47.2.20

**Other mods:**
~120 others, but the main one and the one I can replicate this with is Quark.

**Logs:**
*Even if the game does not crash they may be useful!*
[2024-02-09-1.log.gz](https://github.com/AstralOrdana/Immersive-Weathering/files/14224324/2024-02-09-1.log.gz)
[crash-2024-02-09_11.41.43-client.txt](https://github.com/AstralOrdana/Immersive-Weathering/files/14224319/crash-2024-02-09_11.41.43-client.txt)

**To Reproduce:**
Steps to reproduce the behavior. Format it as a numbered list of steps.

1. Have Immersive Weathering and Quark installed
2. Try to apply Immersive Weathering's "moss clump" onto a piece of cobble.
3. Game crashes.

**Expected behavior:**
Moss to appear.

**Screenshots:**
N/A

**Additional info:**
N/A

**Comment by AstralOrdana** [comment] 2024-02-12 16:54
is this on a server?

**Comment by misfit-stag** [comment] 2024-02-12 18:47
I was in a singleplayer world when testing. No server to test if it would happen there, but I suspect so.

**Comment by AstralOrdana** [comment] 2024-02-13 06:41
duplicate of #325

**Closed as completed by AstralOrdana** 2024-02-13 06:41 UTC
Labels: 1. High priority, Verified 1.20.1+
